# Generated by Django 2.2.10 on 2020-06-15 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_fecha_creacion', models.DateField(auto_now=True)),
                ('carrito_vendido', models.BooleanField(default=False)),
                ('carrito_estado', models.CharField(max_length=50, verbose_name='Carrito Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('producto_marca', models.CharField(blank=True, max_length=50, verbose_name='Marca Producto')),
                ('producto_modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo Producto')),
                ('producto_precio', models.CharField(blank=True, max_length=50, verbose_name='Precio Producto')),
                ('producto_calificacion', models.CharField(default='Bueno', max_length=50, verbose_name='Calificacion Producto')),
                ('producto_fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_costo_total', models.CharField(max_length=50, verbose_name='Costo Total')),
                ('venta_fecha_venta', models.DateField(auto_now=True, verbose_name='Fecha Venta')),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_f.Carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion_nombre', models.CharField(max_length=50, verbose_name='Nombre Promoción')),
                ('promocion_descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('promocion_fecha_creacion', models.CharField(max_length=50, verbose_name='Fecha Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(default='0', max_length=50, verbose_name='Celular')),
                ('direccion', models.CharField(default='', max_length=150, verbose_name='Dirección')),
                ('ciudad', models.CharField(choices=[('La paz', 'La Paz'), ('El Alto', 'El Alto')], default='La Paz', max_length=50, verbose_name='Ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_foto', models.ImageField(default='fotos/productos/none.jpeg', upload_to='fotos/productos/', verbose_name='Producto Foto')),
                ('foto_descripcion', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
                ('foto_fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_has_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_f.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ManyToManyField(through='app_f.Carrito_has_Producto', to='app_f.Producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
