# Generated by Django 2.2.10 on 2020-06-15 02:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_f', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_producto',
            name='foto_foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Producto Fot'),
        ),
    ]
