# Generated by Django 2.2.10 on 2020-06-15 02:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_f', '0002_auto_20200615_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_producto',
            name='foto_foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
