# Generated by Django 2.2.10 on 2020-06-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_f', '0003_auto_20200615_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_producto',
            name='foto_foto',
            field=models.ImageField(default='fotos/productos/none.jpeg', upload_to='fotos/productos/', verbose_name='Producto Foto'),
        ),
    ]
