# Generated by Django 2.2.10 on 2020-06-15 03:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_f', '0004_auto_20200615_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto_producto',
            name='foto_foto2',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
